"""Plug-in dynamic programming benchmark for the execution-stage problem.

The mid-route handoff decision is a finite-horizon optimal stopping problem
on the filtration generated by the running net-load W_k. The EXACT solution
method for this class is backward dynamic programming on the (k, W) state
space — the preventive-restocking DP tradition of the stochastic VRP
literature — not a mixed-integer solver: MIP technology addresses
deterministic (or scenario-tree) programs and cannot represent a
non-anticipativity-constrained multistage stopping rule compactly.

This module implements the standard nonparametric plug-in estimator of that
DP: discretize W_k into quantile bins, estimate the continuation value of
each bin by backward induction over a training sample, and act greedily.
With bins -> infinity and sample size -> infinity it converges to the
optimal policy measurable w.r.t. (k, W_k) — the same information set OTR-2.0
uses. Run with a very large sample it is therefore a near-exact benchmark:
if OTR-2.0 matches it, OTR-2.0 is near-optimal in its policy class.

The interface mirrors core.costs.fit_lsm_general: fit_dp returns a dict of
per-step models exposing .predict(W) -> continuation cost, so the fitted DP
plugs directly into _simulate_costs_general / _simulate_costs_v2.

Public API
----------
fit_dp -- backward induction with binned conditional means
"""

from __future__ import annotations

import numpy as np

from .otr2 import _overflow_step, _ConstantModel


class _BinnedModel:
    """Piecewise-constant conditional-mean estimator on W bins."""

    def __init__(self, edges: np.ndarray, values: np.ndarray):
        self.edges = edges          # inner bin edges, len n_bins - 1
        self.values = values        # bin values, len n_bins

    def predict(self, x):
        idx = np.searchsorted(self.edges, np.asarray(x, dtype=float), side="right")
        return self.values[idx]


def _fill_gaps(values: np.ndarray) -> np.ndarray:
    """Fill empty (nan) bins from the nearest populated neighbour below,
    then above — keeps the estimate defined on the whole real line."""
    v = values.copy()
    n = len(v)
    last = np.nan
    for i in range(n):
        if np.isnan(v[i]):
            v[i] = last
        else:
            last = v[i]
    nxt = np.nan
    for i in range(n - 1, -1, -1):
        if np.isnan(v[i]):
            v[i] = nxt
        else:
            nxt = v[i]
    return v


def fit_dp(
    g_hist: np.ndarray,
    B: float,
    H: np.ndarray,
    E: np.ndarray,
    n_bins: int | None = None,
) -> dict:
    """Fit the plug-in DP by backward induction with binned conditional means.

    Parameters
    ----------
    g_hist : np.ndarray, shape (N, m)
        Training net increments.
    B : float
        Slack; a route breaches when its running sum exceeds B.
    H, E : np.ndarray, shape (m,)
        Per-stop handoff / emergency price schedules. Pass constant vectors
        (omegaF, Cfail) for the flat two-price model.
    n_bins : int, optional
        Number of quantile bins for W_k. Default: clip(N // 30, 8, 256) —
        about 30 samples per bin, capped for stability and resolution.

    Returns
    -------
    dp_models : dict[int -> model]
        dp_models[k].predict([w])[0] = binned estimate of the expected cost
        of continuing past step k with W_k = w under the DP-greedy policy.
        Keys 1 .. m-1, same convention as fit_lsm / fit_lsm_general.
    """
    N, m = g_hist.shape
    if n_bins is None:
        n_bins = int(np.clip(N // 30, 8, 256))

    cum = np.cumsum(g_hist, axis=1)
    ostep = _overflow_step(cum, B)

    future = np.zeros(N)
    breached = ostep <= m
    future[breached] = E[np.clip(ostep[breached] - 1, 0, m - 1)]

    dp_models: dict = {}
    for k in range(m - 1, 0, -1):
        alive = ostep > k
        n_alive = int(alive.sum())
        if n_alive < 2:
            dp_models[k] = _ConstantModel(
                float(future[alive][0]) if n_alive == 1 else float(E[min(k, m - 1)])
            )
            continue

        W = cum[:, k - 1]
        Wa = W[alive]
        nb = min(n_bins, max(1, n_alive // 2))
        # inner edges at alive-sample quantiles -> equal-count bins
        edges = np.unique(np.quantile(Wa, np.linspace(0, 1, nb + 1)[1:-1]))
        idx_a = np.searchsorted(edges, Wa, side="right")
        nb_eff = len(edges) + 1

        sums = np.bincount(idx_a, weights=future[alive], minlength=nb_eff)
        cnts = np.bincount(idx_a, minlength=nb_eff)
        with np.errstate(invalid="ignore"):
            vals = np.where(cnts > 0, sums / np.maximum(cnts, 1), np.nan)
        vals = _fill_gaps(vals)

        model = _BinnedModel(edges, vals)
        dp_models[k] = model

        # greedy DP update on the training paths themselves
        pred = model.predict(W)
        stop = alive & (pred > H[k - 1])
        future = future.copy()
        future[stop] = H[k - 1]

    return dp_models
